 import = [
  # uncomment the flavour you want below:
   # "~/.config/alacritty/catppuccin-latte.toml"
   # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
     "~/.config/alacritty/catppuccin-mocha.toml"
]
  [window]

   # Spread additional padding evenly around the terminal content.
dynamic_padding =  true
opacity = 0.999

decorations = "None"
startup_mode = "Maximized"

padding.x = 16
padding.y = 16

 [font]

normal.family = "AnonymicePro Nerd Font"
bold.family = "AnonymicePro Nerd Font"
italic.family = "AnonymicePro Nerd Font"
bold_italic.family = "AnonymicePro Nerd Font"

size = 20.0

 [env]
TERM = "xterm-256color"












